[theme]
name = "black-metal-gorgoroth"

[colors]
AlertInfo = "#8fb9d3"
AlertWarn = "#ffd966"
AlertError = "#e67373"
Annotation = "#b294bb"
Base = "#c1c1c1"
Guidance = "#aaaaaa"
Important = "#e67373"
Title = "#8fb9d3"
