[theme]
name = "black-metal-gorgoroth"

[colors]
AlertInfo = "#81a2be"
AlertWarn = "#f0c674"
AlertError = "#cc6666"
Annotation = "#b294bb"
Base = "#c1c1c1"
Guidance = "#aaaaaa"
Important = "#cc6666"
Title = "#81a2be"
