[manager]
show_hidden = true
sort_dir_first = true

[preview]
max_width = 80
max_height = 10

[opener]
edit = ["$EDITOR" "$@"]
extract = ["unar" "$1"]
play = ["mpv" "$1"]

[open]
rules = [
	{ name = "Open", use = ["open", "$@"], cond = 'is_dir()' },
	{ name = "Edit", use = ["$EDITOR", "$@"], cond = 'is_file()' },
]