vmType: vz

images:
  - location: "https://github.com/nixos-lima/nixos-lima/releases/download/v0.0.4/nixos-lima-v0.0.4-aarch64.qcow2"
    arch: "aarch64"
    digest: "sha512:a274d225c41918da7f1bb0bc1fde8cc713ed0d36954c21cc26ae403d47879a00f4c3d5601c67c647df87f6f321e1b694140b671910b15a011872311b960569b2"
  - location: "https://github.com/nixos-lima/nixos-lima/releases/download/v0.0.4/nixos-lima-v0.0.4-x86_64.qcow2"
    arch: "x86_64"
    digest: "sha512:5daac286d415a579ca659a98de864fe04ab7a1879d4e4608e3edcd2e931f1848f88ed07316e69a1131ab35b88158b999a21cc5ccf9be9c3d04f51a7e58dc8580"

cpus: 6
memory: "12GiB"
disk: "100GiB"

mounts:
  - location: "~"
    writable: false
  - location: "/tmp/lima"
    writable: true

ssh:
  loadDotSSHPubKeys: true
  forwardAgent: true

containerd:
  system: false
  user: false
