# yaml-language-server: $schema=https://gh-dash.dev/schema.json

prSections:
  - title: "Open Requests"
    filters: "is:open"
  - title: "My Pull Requests"
    filters: "is:open author:@me"
  - title: "Needs My Review"
    filters: "is:open review-requested:@me"
  - title: "Involved"
    filters: "is:open involves:@me -author:@me"

pager:
  diff: delta

defaults:
  refetchIntervalMinutes: 1

theme:
  ui:
    table:
      compact: true
